services:
  devcontainer:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    volumes:
      - ..:/workspaces/data-structures-and-algorithms:cached
      - ~/.gitconfig:/root/.gitconfig:ro
    command: /bin/sh -c "while sleep 1000; do :; done"
